"""create requirements table

Revision ID: b067c2bda1f3
Revises: f7481f9c8af7
Create Date: 2026-08-02 17:28:18.861024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b067c2bda1f3'
down_revision: Union[str, Sequence[str], None] = 'f7481f9c8af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Not Started', 'In Progress', 'Done', name='requirement_status'), nullable=False),
    sa.Column('priority', sa.Enum('Critical', 'High', 'Medium', 'Low', name='priority'), nullable=False),
    sa.Column('backlog_status', sa.Enum('In Backlog', 'Active', name='backlog_status'), nullable=True),
    sa.Column('recommended_approach', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_project_id'), 'requirements', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirements_project_id'), table_name='requirements')
    op.drop_table('requirements')
    # ### end Alembic commands ###
